branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.8

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

    - os: linux
      arch: arm64-graviton2
      virt: vm
      group: edge
      dist: focal
      language: generic

before_cache:
  # Cleanup to avoid the cache to grow indefinitely as new package versions are released
  # see https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew cleanup
    fi

cache:
  directories:
    # Cache downloaded bottles
    - $HOME/Library/Caches/Homebrew
    # pyenv
    - $HOME/.pyenv_cache
    - $HOME/.pyenv/versions/3.7.8
    - $HOME/.pyenv/versions/2.7.15
    # scikit-ci-addons
    - $HOME/downloads

before_install:
  - |
    # Workaround the following error occuring because python installation is cached but gettext dependency is not
    #   dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    #     Referenced from: /Users/travis/.pyenv/versions/3.7.2/bin/python
    #     Reason: Incompatible library version: python requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
    if [[ "$TRAVIS_OS_NAME" == "osx" && "${PYTHON_VERSION}" == "3.7.8" ]]; then
      brew install gettext
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python
        python scripts/ssl-check.py
        python -m pip install --disable-pip-version-check --upgrade pip
        pip install -U scikit-ci scikit-ci-addons
        ci_addons --install ../addons
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run -t --rm \
            -v $(pwd):/io \
            --env TRAVIS=True \
            --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}" \
            quay.io/pypa/manylinux2014_aarch64 \
            /io/scripts/manylinux2014-aarch64-build-and-test-wheel.sh
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ci install
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        pip install twine
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ci test
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ci after_test
    fi
    pwd && ls dist; PATH=~/.pyenv/versions/${PYTHON_VERSION}/bin/:$PATH && twine --version

deploy:
  # deploy-release
  - provider: script
    script: pwd && ls dist;echo "deploy-release" && PATH=~/.pyenv/versions/${PYTHON_VERSION}/bin/:$PATH && twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
  # deploy-master
  - provider: script
    script: pwd && ls dist;echo "deploy-master" && echo "not implemented"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master

env:
  global:
    # PYPI_USER
    - secure: "Xejg5qGnAyo3G+/TaaAr1uHzDv9GLo3mxi6Aw/hZc9gF9lYix1TvkfE6GEBKdPgSLJSqF9NJrwKTt37XH1DjSRLG+qw6Bt1goi5Bkugdk+SC5qmMkvAoG0EKyD119WS4ObrpzqAFcOQqG+4F6iDkSuJLA+dzA3yAzTME4pkhr/2dn0krOSqIcTlgifPwhEaMgo//WRT2dEBM5dWoehXsEMD7VMOUyC0DlV15lKTPKSzTrDEUPU7UFnXgIqZM/brEPbWPQr5Jzgu7BeBk6bmPiiYeh28Cq2juzOzA+JWcGgJmXOfsImYwYuAWZrf0pkE0uQjLySvIBKT7phJv05eNqIxmv/wHK1BPcyMV+2IgFR4+f5ty6C4VUV0hT0HvHr3pMa/8A/5wSNCShEAMTHrwPM5VPWFJtUKTtS5+wwNQDI39MLk/vr9ZTo+y3WJHPaRR0nRpbA3nXFHSqoJJunoMyeI8x9cXZvJ9IENMxGuo3CfBT5RGZamfqSTgn6NjL51ArIMKpvUfm3tXTtlvCHenED1ZQeJI1nWZEalxl8pTyAZoA8S1+h8wraZrUPzhM0QuVpw7vZQeOYu2VSdHO46yxUWoQyb+JWrDTN7EC8vOl7QQzIQlqOWJB5uDJD7UlKKtneTHJrdfXvGxS/hf+Y+hFZK7r+/PDPS6aQjSNDyy+js="
    # PYPI_PASSWORD
    - secure: "iEHYaOC/yivDupsbRzohWYCwFMZbCfT2hYOM96akQtOfd1d37rqFCFjDKr3BNyvHyHzj+uNQ7IblynWAqu3cax2Z8b9YuIFXFAslD76IIgeIhxmi8jPtamMK0NBXam/LEL49EIVXUnwVZrWjnLcJxVaBHGS/9Ft3zWP5Gspa4G1yAJDhNfs+jrFipxO4DOBie9mGI2jFdbFRgcCYoY6Jo4y95zxUG1YF5e+8sUobLoBgVqyaJP4SP/Zu/4CEWMfJev8EjLBzzkoPwOU+hC09qwf2FQCvBXFrudpjPpY23WDFeKf+LcMoW9tIoUmP6UJcQibqHeidimrbo9jST0+wTo1NYjrvriKrlMho/QS4iYkd5N6DGUrhSXEMSiqfdMjVGDZ00wvCsT3DwqE9eG7K+Kw09enchjcZcggZIt9crqZPJg3GMdSwPYTlRpf2OQmE4OHL3pN5dSH5Es/sb0X1G6JQgB/2Ia9Aks2ywYEdzUZhbMqfLVx75bVS4bLfYMAMhE/j7NxpYaUlVkFhz3srLhnrYyAcvCQ6XF4cSeFfxD1ie62/qFIF/QH5u76t91uURHygvNdyJCNHhVJnnWgN9kPsJxfyfdOC2Dnrz/jJcw5irsgQVO2/K4iyGyBVoOqwwpymjoCkxB8capEoLRNLcwyQqCTBnMtGykyRYF2I7FA="
